version: '3'
services:
   database:
     image: mysql
     volumes:
       - my_data:/var/lib/mysql
     networks:
       - my_network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: dbuser
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - database
     image: wordpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: database:3306
       WORDPRESS_DB_USER: dbuser
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: dbuser
     networks:
       - my_network

volumes:
    my_data:

networks:
    my_network: