apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: training
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 32000
  selector:
    app: node